# Generated by Django 3.2.9 on 2021-11-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vriti_app', '0002_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
