# Generated by Django 3.2.9 on 2021-11-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vriti_app', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
